package data.scripts.world.nightcross;

import com.fs.starfarer.api.Global;
import com.fs.starfarer.api.campaign.*;
import com.fs.starfarer.api.impl.campaign.enc.AbyssalRogueStellarObjectEPEC;
import com.fs.starfarer.api.impl.campaign.ids.*;
import com.fs.starfarer.api.impl.campaign.procgen.*;
import com.fs.starfarer.api.impl.campaign.procgen.themes.BaseThemeGenerator;
import com.fs.starfarer.api.impl.campaign.procgen.themes.RemnantStationFleetManager;
import com.fs.starfarer.api.impl.campaign.procgen.themes.SalvageEntityGeneratorOld;
import com.fs.starfarer.api.impl.campaign.rulecmd.salvage.special.BaseSalvageSpecial;
import com.fs.starfarer.api.impl.campaign.shared.WormholeManager;
import com.fs.starfarer.api.impl.campaign.terrain.*;
import com.fs.starfarer.api.util.Misc;
import com.fs.starfarer.api.util.WeightedRandomPicker;
import data.scripts.campaign.enc.NA_BlackHoleMoteScript;
import data.scripts.campaign.ids.NightcrossID;
import org.lazywizard.lazylib.MathUtils;
import org.lwjgl.util.vector.Vector2f;

import java.awt.*;
import java.util.*;
import java.util.List;

import static data.scripts.world.nightcross.NA_StargazerFleets.createStargazerFleet;

public class NA_BlackcatGen implements SectorGeneratorPlugin {
    // generates happy friendly ai fleets to greet the player on their adventures
    public static void initFactionRelationships(SectorAPI sector) {
    }

    public boolean BlackcatGenerated = false;

    @Override
    public void generate(SectorAPI sector) {


        generate_blackcat(sector);
    }
    public void init(SectorAPI sector) {
        
    }


    public static StarSystemAPI blackcatsystem = null;
    public static SectorEntityToken blackcatstation = null;
    public static PlanetAPI lunargravitywell = null;

    protected static Random random = null;

    public boolean generate_blackcat(SectorAPI sector) {


        StarSystemAPI system = sector.createStarSystem("Nix");
        system.setOptionalUniqueId("na_blackcatsystem");
        system.addTag(Tags.THEME_HIDDEN);
        system.addTag(Tags.THEME_SPECIAL);
        system.addTag(Tags.SYSTEM_ABYSSAL);
        system.getAutogeneratedJumpPointsInHyper().forEach(loc -> loc.addTag(Tags.STAR_HIDDEN_ON_MAP));
        system.getAutogeneratedJumpPointsInHyper().forEach(loc -> loc.setDiscoverable(true));
        float w = Global.getSettings().getFloat("sectorWidth");
        float h = Global.getSettings().getFloat("sectorHeight");
        system.getLocation().set(-w/2f - 7300f, -h/2f - 4100f);


        LocationAPI hyper = Global.getSector().getHyperspace();

        system.setBackgroundTextureFilename("graphics/backgrounds/na_blackbg3.jpg");


        Random random = StarSystemGenerator.random;
        this.random = random;
        // create the star and generate the hyperspace anchor for this system
        PlanetAPI star = system.initStar("na_blackcatstar", // unique id for this star
                "star_neutron",  // id in planets.json
                100f, 		  // radius (in pixels at default zoom)
                500); // corona radius, from star edge
        setPulsarIfNeutron(system, star, random);
        star.setDiscoverable(true);
        star.setDiscoveryXP(10000f);

        SectorEntityToken magfield = system.addTerrain(Terrain.MAGNETIC_FIELD,
                new MagneticFieldTerrainPlugin.MagneticFieldParams(700f, // terrain effect band width
                        3200f, // terrain effect middle radius
                        star, // entity that it's around
                        2800f, // visual band start
                        3500f, // visual band end
                        new Color(100, 30, 84, 30), // base color
                        1f, // probability to spawn aurora sequence, checked once/day when no aurora in progress
                        new Color(110, 20, 71, 130),
                        new Color(34, 30, 150, 150),
                        new Color(50, 200, 187, 190),
                        new Color(70, 181, 250, 240),
                        new Color(80, 186, 200, 255),
                        new Color(16, 0, 160),
                        new Color(255, 0, 115)
                ));
        magfield.setCircularOrbit(star, 0, 0, 100);



        PlanetAPI gravitywell = system.addPlanet("na_lunargravitywell", // unique id for this star
                star,
                "Lunar Gravity Well",
                "black_hole",  // id in planets.json
                50f,
                100, 9000, 5000);
        setBlackHoleIfBlackHole(system, gravitywell, random);
        lunargravitywell = gravitywell;
        gravitywell.setCustomDescriptionId("na_lunargravitywell");
        gravitywell.setDiscoverable(true);
        gravitywell.setDiscoveryXP(10000f);



        var maxrings = 8;
        for (var i = 0; i < maxrings; i++) {
            if (i == 0) {
                SectorEntityToken accreetion = system.addRingBand(gravitywell, "misc", "rings_dust0", 256f, 1, Color.white, 1024, 512, -80, Terrain.RING, "The Calling");
                accreetion.addTag(Tags.ACCRETION_DISK);
                accreetion.setCircularOrbit(gravitywell, 0, 0, -100);
            } else {
                RingBandAPI accreetion = system.addRingBand(gravitywell, "misc", "rings_dust0", 256f, 1, Color.white, 1024/maxrings, 200 + 512/maxrings + 1024/maxrings * i, -40 - 10 * i);
                accreetion.addTag(Tags.ACCRETION_DISK);
                accreetion.setSpiral(true);
                accreetion.setSpiralFactor(12);
                accreetion.setCircularOrbit(gravitywell, 0, 0, -100);
            }
        }






        gravitywell.addScript(new NA_BlackHoleMoteScript(gravitywell, 2.5f));

        system.addRingBand(star, "misc", "rings_asteroids0", 256f, 1, Color.white, 512f, 15500, 365, Terrain.ASTEROID_BELT, "Remnant of What Once Was");


        system.setLightColor(new Color(162, 140, 205)); // light color in entire system, affects all entities


        PlanetAPI planet = system.addPlanet("na_blackcatsystem_planet", star, "Garden District", Planets.BARREN_VENUSLIKE, 215, 90, 1700, 75);
        planet.getMemoryWithoutUpdate().set("$na_blackcatsystem_planet", true);
        planet.setCustomDescriptionId("na_blackcatsystem_planet");
        planet.getMarket().addCondition(Conditions.NO_ATMOSPHERE);
        planet.getMarket().addCondition(Conditions.VERY_COLD);
        planet.getMarket().addCondition(Conditions.POOR_LIGHT);
        planet.getMarket().addCondition(Conditions.IRRADIATED);
        planet.getMarket().addCondition(Conditions.RUINS_SCATTERED);

        BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
        loc.orbit = Global.getFactory().createCircularOrbit(star, 215,
                1850, 75);
        BaseThemeGenerator.AddedEntity added = BaseThemeGenerator.addEntity(null, system, loc, "naai_blackcatstation", Factions.NEUTRAL);
        blackcatstation = added.entity;
        //added.entity.getMemoryWithoutUpdate().set(MemFlags.SALVAGE_SPEC_ID_OVERRIDE, "na_blackcatstation");
        added.entity.setName("Research Complex");
        added.entity.getMemoryWithoutUpdate().set("$na_blackcatstation", true);
        added.entity.setCustomDescriptionId("na_blackcatstation");

        // add the links if they werent generated already
        for (StarSystemAPI sys: Global.getSector().getStarSystems()) {
            if (sys != null && sys.getAllEntities() != null) {
                for (SectorEntityToken entity: sys.getAllEntities()) {
                    if (entity != null && entity.getCustomEntityType() != null && entity.getCustomEntityType().equals("naai_research_stargazerstation")) {
                        NA_NightcrossThemeGenerator.linkToMothership(entity, blackcatstation);
                    }
                }
            }
        }


        int maxFleets = 7;
        StargazerStation activeFleets = new StargazerStation(
                added.entity, 1f, 0, maxFleets, 15f, 8, 24);
        system.addScript(activeFleets);



        //CargoAPI cargo = Global.getFactory().createCargo(true);
        //cargo.addCommodity(Commodities.RARE_METALS, 200f + random.nextInt(101));
        //BaseSalvageSpecial.addExtraSalvage(added.entity, cargo);


        planet = system.addPlanet("na_blackcatsystem_planet2", star, "Oxygen Ocean", Planets.BARREN_CASTIRON, 70, 45, 3700, 135);
        planet.setCustomDescriptionId("na_blackcatsystem_planet");
        planet.getMarket().addCondition(Conditions.NO_ATMOSPHERE);
        planet.getMarket().addCondition(Conditions.VERY_COLD);
        planet.getMarket().addCondition(Conditions.POOR_LIGHT);
        planet.getMarket().addCondition(Conditions.IRRADIATED);
        planet.getMarket().addCondition(Conditions.RUINS_WIDESPREAD);


        StarSystemGenerator.addStableLocations(system, 1);


        addCaches(system, 1f, 3, 5, createStringPicker(
                "naai_cache", 4f
        ));

        system.autogenerateHyperspaceJumpPoints(true, true);
        system.getAutogeneratedJumpPointsInHyper().forEach(loca -> loca.setDiscoveryXP(1000f));
        system.getAutogeneratedJumpPointsInHyper().forEach(loca -> {
            if (loca.isGasGiantAnchor()) AbyssalRogueStellarObjectEPEC.setAbyssalDetectedRange(loca, HyperspaceAbyssPluginImpl.GAS_GIANT_DETECTED_RANGE);
            else
            if (loca.isStarAnchor()) AbyssalRogueStellarObjectEPEC.setAbyssalDetectedRange(loca, HyperspaceAbyssPluginImpl.STAR_DETECTED_RANGE);
            else AbyssalRogueStellarObjectEPEC.setAbyssalDetectedRange(loca, HyperspaceAbyssPluginImpl.JUMP_POINT_DETECTED_RANGE);
        });
        system.getAutogeneratedNascentWellsInHyper().forEach(loca -> {
            AbyssalRogueStellarObjectEPEC.setAbyssalDetectedRange(loca, HyperspaceAbyssPluginImpl.NASCENT_WELL_DETECTED_RANGE);
        });
        system.getAutogeneratedJumpPointsInHyper().forEach(loca -> loca.addTag(Tags.STAR_HIDDEN_ON_MAP));

        blackcatsystem = system;
        //BlackcatGenerated = true;
        return BlackcatGenerated;
    }


    public void addCaches(StarSystemAPI system, float chanceToAddAny, int min, int max, WeightedRandomPicker<String> cacheTypes) {
        if (random.nextFloat() >= chanceToAddAny) return;

        int num = min + random.nextInt(max - min + 1);
        for (int i = 0; i < num; i++) {
            BaseThemeGenerator.EntityLocation loc = pickHiddenLocation(random, system, 70f, null);
            String type = cacheTypes.pick();
            BaseThemeGenerator.AddedEntity added = addEntity(random, system, loc, type, Factions.NEUTRAL);

        }
    }





    public static BaseThemeGenerator.AddedEntity addEntity(Random random, StarSystemAPI system, WeightedRandomPicker<BaseThemeGenerator.EntityLocation> locs, String type, String faction) {
        BaseThemeGenerator.EntityLocation loc = locs.pickAndRemove();
        return addEntity(random, system, loc, type, faction);
    }

    public static BaseThemeGenerator.AddedEntity addNonSalvageEntity(LocationAPI system, BaseThemeGenerator.EntityLocation loc, String type, String faction) {
        if (loc != null) {
            SectorEntityToken entity = system.addCustomEntity(null, null, type, faction);
            if (loc.orbit != null) {
                entity.setOrbit(loc.orbit);
                loc.orbit.setEntity(entity);
            } else {
                entity.setOrbit(null);
                entity.getLocation().set(loc.location);
            }
            BaseThemeGenerator.AddedEntity data = new BaseThemeGenerator.AddedEntity(entity, loc, type);
            return data;
        }
        return null;
    }

    public static BaseThemeGenerator.AddedEntity addEntityAutoDetermineType(Random random, LocationAPI system, BaseThemeGenerator.EntityLocation loc, String type, String faction) {
        if (SalvageEntityGeneratorOld.hasSalvageSpec(type)) {
            return addEntity(random, system, loc, type, faction);
        } else {
            return addNonSalvageEntity(system, loc, type, faction);
        }
    }

    public static BaseThemeGenerator.AddedEntity addEntity(Random random, LocationAPI system, BaseThemeGenerator.EntityLocation loc, String type, String faction) {
        if (loc != null) {
            if (random == null) random = StarSystemGenerator.random;
            SectorEntityToken entity = addSalvageEntity(random, system, type, faction);
            if (loc.orbit != null) {
                entity.setOrbit(loc.orbit);
                loc.orbit.setEntity(entity);
            } else {
                entity.setOrbit(null);
                entity.getLocation().set(loc.location);
            }
            BaseThemeGenerator.AddedEntity data = new BaseThemeGenerator.AddedEntity(entity, loc, type);
            return data;
        }
        return null;
    }


    public static SectorEntityToken addSalvageEntity(LocationAPI location, String id, String faction) {
        return addSalvageEntity(null, location, id, faction);
    }
    public static SectorEntityToken addSalvageEntity(Random random, LocationAPI location, String id, String faction) {
        return addSalvageEntity(random, location, id, faction, null);
    }
    public static SectorEntityToken addSalvageEntity(LocationAPI location, String id, String faction, Object pluginParams) {
        return addSalvageEntity(null, location, id, faction, pluginParams);
    }

    public static SectorEntityToken addSalvageEntity(Random random, LocationAPI location, String id, String faction, Object pluginParams) {
        if (random == null) random = StarSystemGenerator.random;
        SalvageEntityGenDataSpec spec = SalvageEntityGeneratorOld.getSalvageSpec(id);

        CustomCampaignEntityAPI entity = location.addCustomEntity(null, spec.getNameOverride(), id, faction, pluginParams);

        if (spec.getRadiusOverride() > 0) {
            entity.setRadius(spec.getRadiusOverride());
        }

        switch (spec.getType()) {
            case ALWAYS_VISIBLE:
                entity.setSensorProfile(null);
                entity.setDiscoverable(null);
                break;
            case DISCOVERABLE:
                entity.setSensorProfile(1f);
                entity.setDiscoverable(true);
                break;
            case NOT_DISCOVERABLE:
                entity.setSensorProfile(1f);
                entity.setDiscoverable(false);
                break;
        }

        long seed = random.nextLong();
        entity.getMemoryWithoutUpdate().set(MemFlags.SALVAGE_SEED, seed);

        entity.getDetectedRangeMod().modifyFlat("gen", spec.getDetectionRange());

        return entity;
    }



    public WeightedRandomPicker<String> createStringPicker(Object ... params) {
        return createStringPicker(random, params);
    }

    public static WeightedRandomPicker<String> createStringPicker(Random random, Object ... params) {
        if (random == null) random = StarSystemGenerator.random;
        WeightedRandomPicker<String> picker = new WeightedRandomPicker<String>(random);
        for (int i = 0; i < params.length; i += 2) {
            String item = (String) params[i];
            float weight = 0f;
            if (params[i+1] instanceof Float) {
                weight = (Float) params[i+1];
            } else if (params[i+1] instanceof Integer) {
                weight = (Integer) params[i+1];
            }
            picker.add(item, weight);
        }
        return picker;
    }


    protected void setPulsarIfNeutron(StarSystemAPI system, PlanetAPI star, Random random) {
        if (star == null) return;

        if (star.getSpec().getPlanetType().equals("star_neutron")) {
            StarCoronaTerrainPlugin coronaPlugin = Misc.getCoronaFor(star);
            if (coronaPlugin != null) {
                system.removeEntity(coronaPlugin.getEntity());
            }

            system.addCorona(star,
                    300, // radius
                    3, // wind
                    0, // flares
                    3); // cr loss


            StarGenDataSpec starData = (StarGenDataSpec) Global.getSettings().getSpec(StarGenDataSpec.class, star.getSpec().getPlanetType(), false);
            float corona = star.getRadius() * (starData.getCoronaMult() + starData.getCoronaVar() * (random.nextFloat() - 0.5f));
            if (corona < starData.getCoronaMin()) corona = starData.getCoronaMin();

            SectorEntityToken eventHorizon = system.addTerrain(Terrain.PULSAR_BEAM,
                    new StarCoronaTerrainPlugin.CoronaParams(star.getRadius() + corona, (star.getRadius() + corona) / 2f,
                            star, starData.getSolarWind(),
                            (float) (starData.getMinFlare() + (starData.getMaxFlare() - starData.getMinFlare()) * random.nextFloat()),
                            starData.getCrLossMult()));
            eventHorizon.setCircularOrbit(star, 0, 0, 100);
        }
    }



    protected void setBlackHoleIfBlackHole(StarSystemAPI system, PlanetAPI star, Random random) {
        if (star == null) return;

        if (star.getSpec().getPlanetType().equals("black_hole")) {
            StarCoronaTerrainPlugin coronaPlugin = Misc.getCoronaFor(star);
            if (coronaPlugin != null) {
                system.removeEntity(coronaPlugin.getEntity());
            }

            StarGenDataSpec starData = (StarGenDataSpec) Global.getSettings().getSpec(StarGenDataSpec.class, star.getSpec().getPlanetType(), false);
            float corona = star.getRadius() * (starData.getCoronaMult() + starData.getCoronaVar() * (random.nextFloat() - 0.5f));
            if (corona < starData.getCoronaMin()) corona = starData.getCoronaMin();

            SectorEntityToken eventHorizon = system.addTerrain(Terrain.EVENT_HORIZON,
                    new StarCoronaTerrainPlugin.CoronaParams(star.getRadius() + corona, (star.getRadius() + corona) / 2f,
                            star, starData.getSolarWind(),
                            (float) (starData.getMinFlare() + (starData.getMaxFlare() - starData.getMinFlare()) * random.nextFloat()),
                            starData.getCrLossMult()));
            eventHorizon.setCircularOrbit(star, 0, 0, 100);
        }
    }






















    public static BaseThemeGenerator.EntityLocation pickHiddenLocation(Random random, StarSystemAPI system, float gap, Set<SectorEntityToken> exclude) {
        if (random == null) random = StarSystemGenerator.random;
        LinkedHashMap<BaseThemeGenerator.LocationType, Float> weights = new LinkedHashMap<BaseThemeGenerator.LocationType, Float>();
        weights.put(BaseThemeGenerator.LocationType.IN_ASTEROID_BELT, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_ASTEROID_FIELD, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_RING, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_SMALL_NEBULA, 5f);
        weights.put(BaseThemeGenerator.LocationType.L_POINT, 5f);
        //weights.put(BaseThemeGenerator.LocationType.GAS_GIANT_ORBIT, 5f);
        weights.put(BaseThemeGenerator.LocationType.NEAR_STAR, 5f);
        //weights.put(BaseThemeGenerator.LocationType.OUTER_SYSTEM, 5f);
        WeightedRandomPicker<BaseThemeGenerator.EntityLocation> locs = getLocations(random, system, exclude, gap, weights);
        if (locs.isEmpty()) {
            return pickAnyLocation(random, system, gap, exclude);
        }
        return locs.pick();
    }

    public static BaseThemeGenerator.EntityLocation pickHiddenLocationNotNearStar(Random random, StarSystemAPI system, float gap, Set<SectorEntityToken> exclude) {
        if (random == null) random = StarSystemGenerator.random;
        LinkedHashMap<BaseThemeGenerator.LocationType, Float> weights = new LinkedHashMap<BaseThemeGenerator.LocationType, Float>();
        weights.put(BaseThemeGenerator.LocationType.IN_ASTEROID_BELT, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_ASTEROID_FIELD, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_RING, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_SMALL_NEBULA, 5f);
        weights.put(BaseThemeGenerator.LocationType.L_POINT, 5f);
        //weights.put(BaseThemeGenerator.LocationType.GAS_GIANT_ORBIT, 5f);
        //weights.put(BaseThemeGenerator.LocationType.OUTER_SYSTEM, 5f);
        WeightedRandomPicker<BaseThemeGenerator.EntityLocation> locs = getLocations(random, system, exclude, gap, weights);
        if (locs.isEmpty()) {
            return pickAnyLocation(random, system, gap, exclude);
        }
        return locs.pick();
    }



    public static BaseThemeGenerator.EntityLocation pickAnyLocation(Random random, StarSystemAPI system, float gap, Set<SectorEntityToken> exclude) {
        if (random == null) random = StarSystemGenerator.random;
        LinkedHashMap<BaseThemeGenerator.LocationType, Float> weights = new LinkedHashMap<BaseThemeGenerator.LocationType, Float>();
        weights.put(BaseThemeGenerator.LocationType.PLANET_ORBIT, 10f);
        weights.put(BaseThemeGenerator.LocationType.STAR_ORBIT, 10f);
        weights.put(BaseThemeGenerator.LocationType.IN_ASTEROID_BELT, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_ASTEROID_FIELD, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_RING, 5f);
        weights.put(BaseThemeGenerator.LocationType.IN_SMALL_NEBULA, 5f);
        weights.put(BaseThemeGenerator.LocationType.L_POINT, 5f);
        //weights.put(BaseThemeGenerator.LocationType.GAS_GIANT_ORBIT, 5f);
        weights.put(BaseThemeGenerator.LocationType.JUMP_ORBIT, 5f);
        weights.put(BaseThemeGenerator.LocationType.NEAR_STAR, 5f);
        //weights.put(BaseThemeGenerator.LocationType.OUTER_SYSTEM, 5f);
        WeightedRandomPicker<BaseThemeGenerator.EntityLocation> locs = getLocations(random, system, exclude, gap, weights);
        return locs.pick();
    }


    public static WeightedRandomPicker<BaseThemeGenerator.EntityLocation> getLocations(Random random, StarSystemAPI system,
                                                                                       float minGap, LinkedHashMap<BaseThemeGenerator.LocationType, Float> weights) {
        return getLocations(random, system, null, minGap, weights);
    }
    public static WeightedRandomPicker<BaseThemeGenerator.EntityLocation> getLocations(Random random, StarSystemAPI system, Set<SectorEntityToken> exclude,
                                                                                       float minGap, LinkedHashMap<BaseThemeGenerator.LocationType, Float> weights) {
        if (random == null) random = StarSystemGenerator.random;
        WeightedRandomPicker<BaseThemeGenerator.EntityLocation> result = new WeightedRandomPicker<BaseThemeGenerator.EntityLocation>(random);

        system.updateAllOrbits();

//		if (system.getType() == StarSystemType.TRINARY_1CLOSE_1FAR) {
//			System.out.println("fwfewfwe");
//		}

        float inner = getInnerRadius(system);
        float outer = getOuterRadius(system);
        //outer += 1000f;
        if (outer < 3000) outer = 3000;
        if (outer > 25000) outer = 25000;

        StarSystemGenerator.StarSystemType systemType = system.getType();

        for (BaseThemeGenerator.LocationType type : weights.keySet()) {
            float weight = weights.get(type);
            List<BaseThemeGenerator.EntityLocation> locs = new ArrayList<BaseThemeGenerator.EntityLocation>();
            switch (type) {
                case PLANET_ORBIT:
                    for (PlanetAPI planet : system.getPlanets()) {
                        //if (planet.isMoon()) continue;
                        if (planet.isGasGiant()) continue;
                        if (planet.isStar()) continue;
                        if (exclude != null && exclude.contains(planet)) continue;

                        float ow = getOrbitalRadius(planet);
                        List<BaseThemeGenerator.OrbitGap> gaps = findGaps(planet, 100f, 100f + ow + minGap, minGap);
                        BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, planet, gaps, type);
                        if (loc != null) locs.add(loc);
                    }
                    break;
                case L_POINT:
                    for (PlanetAPI planet : system.getPlanets()) {
                        if (planet.isStar()) continue;
                        if (planet.isMoon()) continue;
                        if (planet.getRadius() < 100) continue;
                        if (planet.getOrbit() == null || planet.getOrbit().getFocus() == null) continue;
                        if (planet.getCircularOrbitRadius() <= 0) continue;
                        for (StarSystemGenerator.LagrangePointType lpt : EnumSet.of(StarSystemGenerator.LagrangePointType.L4, StarSystemGenerator.LagrangePointType.L5)) {
                            float orbitRadius = planet.getCircularOrbitRadius();
                            float angleOffset = -StarSystemGenerator.LAGRANGE_OFFSET * 0.5f;
                            if (lpt == StarSystemGenerator.LagrangePointType.L5) angleOffset = StarSystemGenerator.LAGRANGE_OFFSET * 0.5f;
                            float angle = planet.getCircularOrbitAngle() + angleOffset;
                            Vector2f location = Misc.getUnitVectorAtDegreeAngle(angle);
                            location.scale(orbitRadius);
                            Vector2f.add(location, planet.getOrbit().getFocus().getLocation(), location);

                            boolean clear = isAreaEmpty(system, location);
                            if (clear) {
                                BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
                                loc.type = type;
                                float orbitDays = planet.getCircularOrbitPeriod();
//							loc.orbit = Global.getFactory().createCircularOrbit(planet.getOrbitFocus(),
//																		angle, orbitRadius, orbitDays);
                                loc.orbit = Global.getFactory().createCircularOrbitWithSpin(planet.getOrbitFocus(),
                                        angle, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
                                locs.add(loc);
                            }
                        }
                    }
                    break;
                case GAS_GIANT_ORBIT:
                    for (PlanetAPI planet : system.getPlanets()) {
                        if (planet.isStar()) continue;
                        if (!planet.isGasGiant()) continue;
                        if (exclude != null && exclude.contains(planet)) continue;

                        float ow = getOrbitalRadius(planet);
                        List<BaseThemeGenerator.OrbitGap> gaps = findGaps(planet, 100f, 100f + ow + minGap, minGap);
                        BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, planet, gaps, type);
                        if (loc != null) locs.add(loc);
                    }
                    break;
                case JUMP_ORBIT:
                    List<SectorEntityToken> jumpPoints = system.getEntitiesWithTag(Tags.JUMP_POINT);
                    for (SectorEntityToken point : jumpPoints) {
                        if (exclude != null && exclude.contains(point)) continue;
                        List<BaseThemeGenerator.OrbitGap> gaps = findGaps(point, 200f, 200f + point.getRadius() + minGap, minGap);
                        BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, point, gaps, type);
                        if (loc != null) locs.add(loc);
                    }
                    break;
                case NEAR_STAR:
                    if (systemType != StarSystemGenerator.StarSystemType.NEBULA) {
                        float r = system.getStar().getRadius();
                        float extra = 500f;
                        r += extra;
                        List<BaseThemeGenerator.OrbitGap> gaps = findGaps(system.getStar(), 200f, 200f + r + minGap, minGap);
                        BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, system.getStar(), gaps, type);
                        if (loc != null) locs.add(loc);

                        if (system.getSecondary() != null) {
                            r = system.getSecondary().getRadius();
                            gaps = findGaps(system.getSecondary(), 200f, 200f + r + minGap, minGap);
                            loc = createLocationAtRandomGap(random, system.getSecondary(), gaps, type);
                            if (loc != null) locs.add(loc);
                        }
                        if (system.getTertiary() != null) {
                            r = system.getTertiary().getRadius();
                            gaps = findGaps(system.getTertiary(), 200f, 200f + r + minGap, minGap);
                            loc = createLocationAtRandomGap(random, system.getTertiary(), gaps, type);
                            if (loc != null) locs.add(loc);
                        }
                    }
                    break;
                case IN_RING:
                    for (CampaignTerrainAPI terrain : system.getTerrainCopy()) {
                        if (exclude != null && exclude.contains(terrain)) continue;
                        //if (terrain.hasTag(Tags.ACCRETION_DISK)) continue;
                        CampaignTerrainPlugin plugin = terrain.getPlugin();
                        if (plugin instanceof RingSystemTerrainPlugin) {
                            RingSystemTerrainPlugin ring = (RingSystemTerrainPlugin) plugin;
                            float start = ring.params.middleRadius - ring.params.bandWidthInEngine / 2f;
                            List<BaseThemeGenerator.OrbitGap> gaps = findGaps(terrain,
                                    start - 100f, start + ring.params.bandWidthInEngine + 100f, minGap);
                            BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, terrain, gaps, type);
                            if (loc != null) locs.add(loc);
                        } else if (plugin instanceof MagneticFieldTerrainPlugin) {
                            MagneticFieldTerrainPlugin ring = (MagneticFieldTerrainPlugin) plugin;
                            float start = ring.getParams().middleRadius - ring.getParams().bandWidthInEngine / 2f;
                            List<BaseThemeGenerator.OrbitGap> gaps = findGaps(terrain,
                                    start - 100f, start + ring.getParams().bandWidthInEngine + 100f, minGap);
                            BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, terrain, gaps, type);
                            if (loc != null) locs.add(loc);
                        }
                    }
                    break;
                case IN_SMALL_NEBULA:
                    for (CampaignTerrainAPI terrain : system.getTerrainCopy()) {
                        if (exclude != null && exclude.contains(terrain)) continue;
                        CampaignTerrainPlugin plugin = terrain.getPlugin();
                        if (plugin instanceof NebulaTerrainPlugin) {
                            NebulaTerrainPlugin nebula = (NebulaTerrainPlugin) plugin;
                            float tilesHigh = nebula.getTiles()[0].length;
                            float tilesWide = nebula.getTiles().length;
                            float ts = nebula.getTileSize();
                            float w = ts * tilesWide;
                            float h = ts * tilesHigh;
                            if (w <= 10000) {
                                float r = (float) Math.sqrt(w * w + h * h);
                                if (terrain.getOrbit() == null) {
                                    Vector2f point = Misc.getPointWithinRadius(terrain.getLocation(), r * 0.5f, random);
                                    BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
                                    loc.type = type;
                                    loc.location = point;
                                    loc.orbit = null;
                                    locs.add(loc);
                                } else {
                                    float min = Math.min(100f, r * 0.25f);
                                    float max = r;
                                    BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
                                    loc.type = type;
                                    float orbitRadius = min + (max - min) * (0.75f * random.nextFloat());
                                    float orbitDays = orbitRadius / (20f + random.nextFloat() * 5f);
                                    loc.orbit = Global.getFactory().createCircularOrbitWithSpin(terrain,
                                            random.nextFloat() * 360f, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
                                    locs.add(loc);
                                }
                            }
                        }
                    }
                    break;
                case IN_ASTEROID_BELT:
                    for (CampaignTerrainAPI terrain : system.getTerrainCopy()) {
                        if (exclude != null && exclude.contains(terrain)) continue;
                        CampaignTerrainPlugin plugin = terrain.getPlugin();
                        if (plugin instanceof AsteroidBeltTerrainPlugin && !(plugin instanceof AsteroidFieldTerrainPlugin)) {
                            AsteroidBeltTerrainPlugin ring = (AsteroidBeltTerrainPlugin) plugin;
                            if (ring.params != null) {
                                float start = ring.params.middleRadius - ring.params.bandWidthInEngine / 2f;
                                List<BaseThemeGenerator.OrbitGap> gaps = findGaps(terrain,
                                        start - 100f, start + ring.params.bandWidthInEngine + 100f, minGap);
                                BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, terrain, gaps, type);
                                if (loc != null) locs.add(loc);
                            } else {
                                //System.out.println("egaegfwgwgew");
                            }
                        }
                    }
                    break;
                case IN_ASTEROID_FIELD:
                    for (CampaignTerrainAPI terrain : system.getTerrainCopy()) {
                        if (exclude != null && exclude.contains(terrain)) continue;
                        CampaignTerrainPlugin plugin = terrain.getPlugin();
                        if (plugin instanceof AsteroidFieldTerrainPlugin) {
                            AsteroidFieldTerrainPlugin ring = (AsteroidFieldTerrainPlugin) plugin;
                            if (isAreaEmpty(system, terrain.getLocation())) {
                                float min = Math.min(100f, ring.params.bandWidthInEngine * 0.25f);
                                float max = ring.params.bandWidthInEngine;
                                BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
                                loc.type = type;
                                float orbitRadius = min + (max - min) * (0.75f * random.nextFloat());
                                float orbitDays = orbitRadius / (20f + random.nextFloat() * 5f);
//							loc.orbit = Global.getFactory().createCircularOrbit(terrain,
//											random.nextFloat() * 360f, orbitRadius, orbitDays);
                                loc.orbit = Global.getFactory().createCircularOrbitWithSpin(terrain,
                                        random.nextFloat() * 360f, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
                                locs.add(loc);

                            }
                        }
                    }
                    break;
                case OUTER_SYSTEM:
                    SectorEntityToken near = pickOuterEntityToSpawnNear(random, system);
//				if (!USE_NEW_SPAWN && near != null) {
//					EntityLocation loc = new EntityLocation();
//					loc.type = type;
//					float orbitRadius = 3000 + 1500f * random.nextFloat();
//					float orbitDays = orbitRadius / (20f + random.nextFloat() * 5f);
//					loc.orbit = Global.getFactory().createCircularOrbitWithSpin(near,
//							random.nextFloat() * 360f, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
//					locs.add(loc);
//				} else {
                    if (near != null && near.getCircularOrbitRadius() > 0) {
                        BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
                        loc.type = type;
                        //					float orbitRadius = 3000 + 1500f * random.nextFloat();
                        //					float orbitDays = orbitRadius / (20f + random.nextFloat() * 5f);
                        ////					loc.orbit = Global.getFactory().createCircularOrbitWithSpin(system.getCenter(),
                        ////							random.nextFloat() * 360f, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
                        //					loc.orbit = Global.getFactory().createCircularOrbitWithSpin(near,
                        //							random.nextFloat() * 360f, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
                        float orbitRadius = near.getCircularOrbitRadius() + 1000f + 1500f * random.nextFloat();
                        float orbitDays = near.getCircularOrbitPeriod();
                        loc.orbit = Global.getFactory().createCircularOrbitWithSpin(system.getCenter(),
                                near.getCircularOrbitAngle() + 15f - 30f * random.nextFloat(),
                                orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
                        locs.add(loc);
                    } else if (near != null) {
                        BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
                        loc.type = type;
                        float orbitRadius = outer + 500f + 500f * random.nextFloat();
                        float orbitDays = orbitRadius / (20f + random.nextFloat() * 5f);
                        loc.orbit = Global.getFactory().createCircularOrbitWithSpin(system.getCenter(),
                                random.nextFloat() * 360f, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
                        locs.add(loc);
                    }
//				}
                    break;
                case STAR_ORBIT:
//				if (system.getType() == StarSystemType.TRINARY_1CLOSE_1FAR) {
//					System.out.println("fwfewfwe");
//				}

                    SectorEntityToken main = system.getCenter();
                    List<SectorEntityToken> secondary = new ArrayList<SectorEntityToken>();
                    switch (system.getType()) {
                        case BINARY_FAR:
                            secondary.add(system.getSecondary());
                            break;
                        case TRINARY_1CLOSE_1FAR:
                            secondary.add(system.getTertiary());
                            break;
                        case TRINARY_2FAR:
                            secondary.add(system.getSecondary());
                            secondary.add(system.getTertiary());
                            break;
                    }

                    if (main != null) {
                        List<BaseThemeGenerator.OrbitGap> gaps = findGaps(main, inner, outer + minGap, minGap);
                        BaseThemeGenerator.EntityLocation loc;
                        for (BaseThemeGenerator.OrbitGap gap : gaps) {
                            loc = createLocationAtGap(random, main, gap, type);
                            if (loc != null) locs.add(loc);
                        }
                    }

                    for (SectorEntityToken star : secondary) {
                        float ow = getOrbitalRadius((PlanetAPI) star);
                        if (ow < 3000) ow = 3000;
                        float r = star.getRadius();
                        List<BaseThemeGenerator.OrbitGap> gaps = findGaps(star, r, ow + r + minGap, minGap);
                        BaseThemeGenerator.EntityLocation loc;
                        for (BaseThemeGenerator.OrbitGap gap : gaps) {
                            loc = createLocationAtGap(random, star, gap, type);
                            if (loc != null) locs.add(loc);
                        }
                    }

                    break;
            }

            // if in nebula, convert circular orbits to fixed locations
            if (system.getType() == StarSystemGenerator.StarSystemType.NEBULA) {
                for (BaseThemeGenerator.EntityLocation loc : locs) {
                    if (loc.orbit != null && loc.orbit.getFocus() == system.getCenter()) {
                        loc.location = loc.orbit.computeCurrentLocation();
                        loc.orbit = null;
                    }
                }
            }

            if (!locs.isEmpty()) {
                float weightPer = weight / (float) locs.size();
                for (BaseThemeGenerator.EntityLocation loc : locs) {
                    result.add(loc, weightPer);
                }
            }

        }

        return result;
    }

    public static BaseThemeGenerator.EntityLocation createLocationAtRandomGap(Random random, SectorEntityToken center, float minGap) {
        if (random == null) random = StarSystemGenerator.random;
        float ow = getOrbitalRadius(center);
        List<BaseThemeGenerator.OrbitGap> gaps = findGaps(center, 100f, 100f + ow + minGap, minGap);
        BaseThemeGenerator.EntityLocation loc = createLocationAtRandomGap(random, center, gaps, BaseThemeGenerator.LocationType.PLANET_ORBIT);
        return loc;
    }


    private static BaseThemeGenerator.EntityLocation createLocationAtRandomGap(Random random, SectorEntityToken center, List<BaseThemeGenerator.OrbitGap> gaps, BaseThemeGenerator.LocationType type) {
        if (gaps.isEmpty()) return null;
        if (random == null) random = StarSystemGenerator.random;
        WeightedRandomPicker<BaseThemeGenerator.OrbitGap> picker = new WeightedRandomPicker<BaseThemeGenerator.OrbitGap>(random);
        picker.addAll(gaps);
        BaseThemeGenerator.OrbitGap gap = picker.pick();
        return createLocationAtGap(random, center, gap, type);
    }

    private static BaseThemeGenerator.EntityLocation createLocationAtGap(Random random, SectorEntityToken center, BaseThemeGenerator.OrbitGap gap, BaseThemeGenerator.LocationType type) {
        if (gap != null) {
            if (random == null) random = StarSystemGenerator.random;
            BaseThemeGenerator.EntityLocation loc = new BaseThemeGenerator.EntityLocation();
            loc.type = type;
            float orbitRadius = gap.start + (gap.end - gap.start) * (0.25f + 0.5f * random.nextFloat());
            float orbitDays = orbitRadius / (20f + random.nextFloat() * 5f);
//			loc.orbit = Global.getFactory().createCircularOrbit(center,
//					random.nextFloat() * 360f, orbitRadius, orbitDays);
            loc.orbit = Global.getFactory().createCircularOrbitWithSpin(center,
                    random.nextFloat() * 360f, orbitRadius, orbitDays, random.nextFloat() * 10f + 1f);
            return loc;
        }
        return null;
    }


    public static class OrbitGap {
        public float start;
        public float end;
    }

    public static class OrbitItem {
        public SectorEntityToken item;
        public float orbitRadius;
        public float orbitalWidth;
    }

    public static List<BaseThemeGenerator.OrbitGap> findGaps(SectorEntityToken center, float minPad, float maxDist, float minGap) {
        List<BaseThemeGenerator.OrbitGap> gaps = new ArrayList<BaseThemeGenerator.OrbitGap>();

        LocationAPI loc = center.getContainingLocation();
        if (loc == null) return gaps;

        List<BaseThemeGenerator.OrbitItem> items = new ArrayList<BaseThemeGenerator.OrbitItem>();
        for (PlanetAPI planet : loc.getPlanets()) {
            if (planet.getOrbitFocus() != center) continue;

            BaseThemeGenerator.OrbitItem item = new BaseThemeGenerator.OrbitItem();
            item.item = planet;
            item.orbitRadius = planet.getCircularOrbitRadius();
            if (item.orbitRadius > maxDist) continue;

            item.orbitalWidth = getOrbitalRadius(planet) * 2f;
            items.add(item);
        }

        for (CampaignTerrainAPI terrain : loc.getTerrainCopy()) {
            if (terrain.getOrbitFocus() != center) continue;

            CampaignTerrainPlugin plugin = terrain.getPlugin();
            if (plugin instanceof StarCoronaTerrainPlugin) continue;
            //if (plugin instanceof MagneticFieldTerrainPlugin) continue;
            //if (plugin instanceof PulsarBeamTerrainPlugin) continue;

            if (plugin instanceof BaseRingTerrain) {
                BaseRingTerrain ring = (BaseRingTerrain) plugin;

                BaseThemeGenerator.OrbitItem item = new BaseThemeGenerator.OrbitItem();
                item.item = terrain;
                item.orbitRadius = ring.params.middleRadius;
                if (item.orbitRadius > maxDist) continue;

                item.orbitalWidth = ring.params.bandWidthInEngine;
                items.add(item);
            } else if (plugin instanceof MagneticFieldTerrainPlugin) {
                MagneticFieldTerrainPlugin ring = (MagneticFieldTerrainPlugin) plugin;

                BaseThemeGenerator.OrbitItem item = new BaseThemeGenerator.OrbitItem();
                item.item = terrain;
                item.orbitRadius = ring.getParams().middleRadius;
                if (item.orbitRadius > maxDist) continue;

                item.orbitalWidth = ring.getParams().bandWidthInEngine;
                items.add(item);
            }
        }

        List<CustomCampaignEntityAPI> entities = loc.getEntities(CustomCampaignEntityAPI.class);
        for (SectorEntityToken custom : entities) {
            if (custom.getOrbitFocus() != center) continue;

            BaseThemeGenerator.OrbitItem item = new BaseThemeGenerator.OrbitItem();
            item.item = custom;
            item.orbitRadius = custom.getCircularOrbitRadius();
            if (item.orbitRadius > maxDist) continue;

            item.orbitalWidth = custom.getRadius() * 2f;
            items.add(item);
        }

        //List<SectorEntityToken> jumpPoints = loc.getEntitiesWithTag(Tags.JUMP_POINT);
        List<SectorEntityToken> jumpPoints = loc.getJumpPoints();
        for (SectorEntityToken point : jumpPoints) {
            if (point.getOrbitFocus() != center) continue;

            BaseThemeGenerator.OrbitItem item = new BaseThemeGenerator.OrbitItem();
            item.item = point;
            item.orbitRadius = point.getCircularOrbitRadius();
            if (item.orbitRadius > maxDist) continue;

            item.orbitalWidth = point.getRadius() * 2f;
            items.add(item);
        }

        Collections.sort(items, new Comparator<BaseThemeGenerator.OrbitItem>() {
            public int compare(BaseThemeGenerator.OrbitItem o1, BaseThemeGenerator.OrbitItem o2) {
                return (int)Math.signum(o1.orbitRadius - o2.orbitRadius);
            }
        });

        float prev = center.getRadius() + minPad;
        for (BaseThemeGenerator.OrbitItem item : items) {
            float next = item.orbitRadius - item.orbitalWidth / 2f;
            if (next - prev >= minGap) {
                BaseThemeGenerator.OrbitGap gap = new BaseThemeGenerator.OrbitGap();
                gap.start = prev;
                gap.end = next;
                gaps.add(gap);
            }
            prev = Math.max(prev, item.orbitRadius + item.orbitalWidth / 2f);
        }

        if (maxDist - prev >= minGap) {
            BaseThemeGenerator.OrbitGap gap = new BaseThemeGenerator.OrbitGap();
            gap.start = prev;
            gap.end = maxDist;
            gaps.add(gap);
        }

        return gaps;
    }


    public static float getInnerRadius(StarSystemAPI system) {
        switch (system.getType()) {
            case NEBULA:
                return 0;
            case DEEP_SPACE:
                return 500f;
            case SINGLE:
            case BINARY_FAR:
            case TRINARY_2FAR:
                if (system.getStar() == null) return 0; // alpha site
                return system.getStar().getRadius();
            case BINARY_CLOSE:
            case TRINARY_1CLOSE_1FAR:
                return Math.max(system.getStar().getCircularOrbitRadius() + system.getStar().getRadius(),
                        system.getSecondary().getCircularOrbitRadius() + system.getSecondary().getRadius());
            case TRINARY_2CLOSE:
                float max = Math.max(system.getStar().getCircularOrbitRadius() + system.getStar().getRadius(),
                        system.getSecondary().getCircularOrbitRadius() + system.getSecondary().getRadius());
                max = Math.max(max,
                        system.getTertiary().getCircularOrbitRadius() + system.getTertiary().getRadius());
                return max;
        }
        return 0;
    }


    public static SectorEntityToken pickOuterEntityToSpawnNear(Random random, StarSystemAPI system) {
        if (random == null) random = StarSystemGenerator.random;

        WeightedRandomPicker<SectorEntityToken> picker = new WeightedRandomPicker<SectorEntityToken>(random);
        float max = getOuterRadius(system);
        float threshold = max * 0.75f;

        for (PlanetAPI planet : system.getPlanets()) {
            float r = planet.getLocation().length() + getOrbitalRadius(planet);
            if (r > threshold) {
                picker.add(planet);
            }
        }

//		for (CampaignTerrainAPI terrain : system.getTerrainCopy()) {
//			CampaignTerrainPlugin plugin = terrain.getPlugin();
//			if (plugin instanceof BaseRingTerrain && !(plugin instanceof PulsarBeamTerrainPlugin)) {
//				BaseRingTerrain ring = (BaseRingTerrain) plugin;
//				float r = ring.params.middleRadius + ring.params.bandWidthInEngine * 0.5f;
//				r += Misc.getDistance(system.getCenter().getLocation(), terrain.getLocation());
//				if (r > threshold) {
//					picker.add(terrain);
//				}
//			} else if (plugin instanceof BaseTiledTerrain) {
//				if (plugin instanceof NebulaTerrainPlugin) continue;
//
//				BaseTiledTerrain tiles = (BaseTiledTerrain) plugin;
//				float r = tiles.getRenderRange();
//				r += Misc.getDistance(system.getCenter().getLocation(), terrain.getLocation());
//				if (r > threshold) {
//					picker.add(terrain);
//				}
//			}
//		}

        List<SectorEntityToken> jumpPoints = system.getEntitiesWithTag(Tags.JUMP_POINT);
        for (SectorEntityToken point : jumpPoints) {
            float r = Misc.getDistance(system.getCenter().getLocation(), point.getLocation());
            r += point.getRadius();
            if (r > threshold) {
                picker.add(point);
            }
        }

        return picker.pick();
    }


    public static float getOuterRadius(StarSystemAPI system) {
        float max = 0f;

        for (PlanetAPI planet : system.getPlanets()) {
            //float r = planet.getCircularOrbitRadius() + getOrbitalRadius(planet);
            float r = planet.getLocation().length() + getOrbitalRadius(planet);
            if (r > max) max = r;
        }

        for (CampaignTerrainAPI terrain : system.getTerrainCopy()) {
            CampaignTerrainPlugin plugin = terrain.getPlugin();

            if (plugin instanceof BaseRingTerrain && !(plugin instanceof PulsarBeamTerrainPlugin)) {
                BaseRingTerrain ring = (BaseRingTerrain) plugin;
                float r = ring.params.middleRadius + ring.params.bandWidthInEngine * 0.5f;
                r += Misc.getDistance(system.getCenter().getLocation(), terrain.getLocation());
                if (r > max) max = r;
            } else if (plugin instanceof BaseTiledTerrain) {
                if (plugin instanceof NebulaTerrainPlugin) continue;

                BaseTiledTerrain tiles = (BaseTiledTerrain) plugin;
                float r = tiles.getRenderRange();
                r += Misc.getDistance(system.getCenter().getLocation(), terrain.getLocation());
                if (r > max) max = r;
            }
        }

//		List<CustomCampaignEntityAPI> entities = system.getEntities(CustomCampaignEntityAPI.class);
//		for (SectorEntityToken custom : entities) {
//			//float r = custom.getCircularOrbitRadius() + custom.getRadius();
//			float r = Misc.getDistance(system.getCenter().getLocation(), custom.getLocation());
//			r += custom.getRadius();
//			if (r > max) max = r;
//		}

        List<SectorEntityToken> jumpPoints = system.getEntitiesWithTag(Tags.JUMP_POINT);
        for (SectorEntityToken point : jumpPoints) {
            float r = Misc.getDistance(system.getCenter().getLocation(), point.getLocation());
            r += point.getRadius();
            if (r > max) max = r;
        }

        return max;
    }

    public static boolean isAreaEmpty(LocationAPI loc, Vector2f coords) {
        //loc.updateAllOrbits();

        float range = 400f;
        for (PlanetAPI planet : loc.getPlanets()) {
            float dist = Misc.getDistance(planet.getLocation(), coords);
            if (dist < range + planet.getRadius()) return false;
        }

        List<CustomCampaignEntityAPI> entities = loc.getEntities(CustomCampaignEntityAPI.class);
        for (SectorEntityToken custom : entities) {
            float dist = Misc.getDistance(custom.getLocation(), coords);
            if (dist < range + custom.getRadius()) {
                return false;
            }
        }

        for (CampaignTerrainAPI terrain : loc.getTerrainCopy()) {
            CampaignTerrainPlugin plugin = terrain.getPlugin();
//			if (plugin instanceof PulsarBeamTerrainPlugin) continue;
//			if (plugin instanceof HyperspaceTerrainPlugin) continue;
//			if (plugin instanceof NebulaTerrainPlugin) continue;
//			if (plugin instanceof BaseRingTerrain) {
            if (plugin instanceof DebrisFieldTerrainPlugin) {
                DebrisFieldTerrainPlugin ring = (DebrisFieldTerrainPlugin) plugin;
                float r = ring.params.middleRadius + ring.params.bandWidthInEngine * 0.5f;
                float dist = Misc.getDistance(terrain.getLocation(), coords);
                if (dist < range + r) return false;
            }
        }

        return true;
    }

    public static float getOrbitalRadius(SectorEntityToken center) {
        LocationAPI loc = center.getContainingLocation();
        if (loc == null) return center.getRadius();

        float max = center.getRadius();
        for (PlanetAPI planet : loc.getPlanets()) {
            if (planet.getOrbitFocus() != center) continue;
            float r = planet.getCircularOrbitRadius() + getOrbitalRadius(planet);
            if (r > max) max = r;
        }

        for (CampaignTerrainAPI terrain : loc.getTerrainCopy()) {
            if (terrain.getOrbitFocus() != center) continue;
            CampaignTerrainPlugin plugin = terrain.getPlugin();

            if (plugin instanceof PulsarBeamTerrainPlugin) continue;
            if (plugin instanceof RadioChatterTerrainPlugin) continue;

            if (plugin instanceof BaseRingTerrain) {
                BaseRingTerrain ring = (BaseRingTerrain) plugin;
                float r = ring.params.middleRadius + ring.params.bandWidthInEngine * 0.5f;
                if (r > max) max = r;
            }
        }

        List<CustomCampaignEntityAPI> entities = loc.getEntities(CustomCampaignEntityAPI.class);
        for (SectorEntityToken custom : entities) {
            if (custom.getOrbitFocus() != center) continue;
            float r = custom.getCircularOrbitRadius() + custom.getRadius();
            if (r > max) max = r;
        }

        return max;
    }


}
